workflows:
    boring-workflow:
        name: Boring Pipeline
        scripts:
          - name: CICD Started
            script: echo "Welcome to your CICD set up"
        publishing:
          email:
            recipients:
              - gabriel.felipo2010@gmail.com
            notify:
              success: true
              failure: true
