workflows:
    boring-workflow:
        name: Boring Pipeline
        scripts:
          - name: CICD Started
            script: echo "Welcome to your CICD set up"
          - name: Build Boring app
            script: xcodebuild build -workspace "Boring.xcworkingspace" - scheme "Boring" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        publishing:
          email:
            recipients:
              - gabriel.felipo2010@gmail.com
            notify:
              success: true
              failure: true
